name: feast-demo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  run:
    name: Feast Demo
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Run Feast Integration Test
        run: uv run feastle/test_feast.py
        env:
          AWS_ACCESS_KEY_ID: "id"
          AWS_SECRET_ACCESS_KEY: "key"
